name: Trigger Netlify Build

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ebdad127c8badced259cea0
