name: Trigger Netlify Build

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */12 * * *'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: echo 'need to fix issue with facebook embed video!'
        #run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ebdad127c8badced259cea0
